[package]
name = "wgpu-template"
version = "0.1.0"
edition = "2024"

[dependencies]
pollster = "0.4.0"
wgpu = { version = "25.0.0", default-features = false, features = ["vulkan", "wgsl"] }
winit = { version = "0.30.10", default-features = false, features = ["rwh_06", "x11"] }
